openapi: "3.0.0"
info:
  description: Documentation for Direct Line Group API.
  version: 0.0.1
  title: Direct Line Group API
tags:
  - name: healthcheck
  - name: total
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            properties:
              error_message:
                type: string
                example: Not valid values.
              error_code:
                type: string
                example: BAD_REQUEST
  schemas:
    Healthcheck:
      description: Status of the service checker
      type: object
      properties:
        message:
          type: string
          example: "Welcome to Direct Line Group!"
paths:
  /:
    get:
      tags:
        - healthcheck
      summary: Check the status of the service
      description: Call this endpoint to check the status of the service
      operationId: healthcheck
      responses:
        '200':
          description: Healthy service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Healthcheck'
  /total:
    post:
      tags:
        - total
      summary: Calculate the sum of a list of numbers.
      description: Provided a bunch of numbers in a list, calculates the sum of all the elements.
      operationId: total
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numbers_to_add:
                  type: array
                  items:
                    type: number
                    example: 1
              required:
                - numbers_to_add
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
                    example: 1
        '400':
          $ref: '#/components/responses/BadRequest'